# Generated by Django 6.0 on 2025-12-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoproject",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
