# Generated by Django 6.0 on 2025-12-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HotTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("Weibo", "Weibo"),
                            ("Zhihu", "Zhihu"),
                            ("Baidu", "Baidu"),
                        ],
                        max_length=32,
                    ),
                ),
                ("hot_value", models.IntegerField(default=0)),
                ("summary", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_used", models.BooleanField(default=False)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("title", "platform"),
                        name="uniq_hot_topic_title_platform",
                    )
                ],
            },
        ),
    ]
