# Generated by Django 6.0 on 2025-12-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hottopic",
            name="platform",
            field=models.CharField(
                choices=[
                    ("Weibo", "Weibo"),
                    ("Zhihu", "Zhihu"),
                    ("Baidu", "Baidu"),
                    ("Douyin", "Douyin"),
                ],
                max_length=32,
            ),
        ),
    ]
